### ISSUE TITLE
Training content should be loaded by slugs only

### ISSUE THREAD

**Issue by thenickcox** [WikiEducationFoundation/WikiEduDashboard#424]
Currently, the YAML file still has names/descriptions, etc. Make sure the loading isn't using these. If so, factor out so that both slide and module loading uses only slugs.

```yaml
# training_content/libraries/students.yml
categories:
  - title: Basics
    description: This is the description of the basic category
    modules:
      - slug: welcome-to-wikipedia
        name: Welcome to Wikipedia
        description: An introduction to Wikipedia
      - slug: policies-and-guidelines
        name: Policies and Guidelines
        description: An overview of Wikipedia's principles and policiess
```
